# render.yaml
# Final, corrected configuration for Cloudivito on Render.
# This version fixes the "invalid service property: url" error by manually
# setting the service URLs, which is the correct approach for public-facing addresses.

services:
  # -----------------
  # Backend Service (Node.js + Express)
  # -----------------
  - type: web
    name: cloudivito-backend
    runtime: node
    rootDir: cloudivito-backend
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      # --- Critical Secrets (set in Render dashboard) ---
      - key: MONGO_URI
        sync: false
      - key: PAYMONGO_SECRET_KEY
        sync: false
      - key: PAYMONGO_WEBHOOK_SECRET
        sync: false

      # --- Generated & Linked Variables ---
      - key: JWT_SECRET
        generateValue: true
      # FIX: Manually set the frontend's public URL.
      # Render's fromService does not expose the public URL.
      - key: CLIENT_URL
        value: https://cloudivito.onrender.com

  # -----------------
  # Frontend Service (React + Vite Static Site)
  # -----------------
  - type: web
    name: cloudivito
    runtime: static
    rootDir: cloudivito-frontend
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      # FIX: Manually set the backend's public URL.
      - key: VITE_API_URL
        value: https://cloudivito-backend.onrender.com/api
