# render.yaml
# Corrected configuration for deploying Cloudivito on Render.
# Defines a Node.js web service (backend) and a static site (frontend).

services:
  # -----------------
  # Backend Service (Node.js + Express)
  # -----------------
  - type: web
    name: cloudivito-backend
    runtime: node
    rootDir: cloudivito-backend
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      # --- Critical Secrets (set in Render dashboard) ---
      - key: MONGO_URI
        sync: false
      - key: PAYMONGO_SECRET_KEY
        sync: false
      - key: PAYMONGO_WEBHOOK_SECRET
        sync: false

      # --- Generated & Linked Variables ---
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          type: static # Correctly points to a static service type
          name: cloudivito-frontend
          property: url # This will now be valid

  # -----------------
  # Frontend Service (React + Vite Static Site)
  # -----------------
  - type: static
    name: cloudivito-frontend
    rootDir: cloudivito-frontend
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist # This is now valid because type is 'static'
    autoDeploy: true
    routes:
      # This is now valid because type is 'static'
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web # Correctly points to a web service type
          name: cloudivito-backend
          property: host # This will now be valid
