# render.yaml
# Final, corrected configuration for Cloudivito on Render.
# This version fixes the "unknown type 'static'" error by correctly defining
# the frontend as a 'web' service with a 'static' runtime.

services:
  # -----------------
  # Backend Service (Node.js + Express)
  # -----------------
  - type: web
    name: cloudivito-backend
    runtime: node
    rootDir: cloudivito-backend
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      # --- Critical Secrets (set in Render dashboard) ---
      - key: MONGO_URI
        sync: false
      - key: PAYMONGO_SECRET_KEY
        sync: false
      - key: PAYMONGO_WEBHOOK_SECRET
        sync: false

      # --- Generated & Linked Variables ---
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          type: web # The frontend is a 'web' service type
          name: cloudivito-frontend
          property: url

  # -----------------
  # Frontend Service (React + Vite Static Site)
  # -----------------
  - type: web # FIX: A static site's type is 'web'.
    name: cloudivito-frontend
    runtime: static # FIX: The runtime is specified as 'static'.
    rootDir: cloudivito-frontend
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web # The backend is a 'web' service type
          name: cloudivito-backend
          property: url
